### ISSUE TITLE
stub wsk and task on the cli

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris-cli#4]
I want to use [kong](https://github.com/alecthomas/kong) to parse the command line.

The first task would be to use it to implement 2 sub commands that stubs the full wsk and task. So

`nuv wsk ...` runs the acutal `wsk ...`
while 
`nuv task ...` runs the actual `task ...`

**Comment by giusdp** [comment]
Hi, would it be fine if I try to tackle this issue? Perhaps with the help of @aviola since we were already helping each other with the wsk and task integration.

**Comment by msciabarra** [comment]
go for it
